# ----------------------------
# SITE META
# ----------------------------
title: "BuWiFi: WiFi Marketing Solution"
description: >
  BuWiFi - WiFi Marketing Solution. Understand Your Customers and Engage Better.
  Transform your guest WiFi into a powerful WiFi marketing tool.
web: https://buwifi.com
keywords: Guest WiFi, Analytics, Personalization, WiFi Marketing, CDP, CRM
name: BuWiFi
product_name: BuWiFi
author: Murat Eren
email: info@buwifi.com
address: "Yoğurtçubaşı Sok. No 18/1 D13, Kadıköy, 34726, İstanbul, Türkiye"
phone: "+90 (532) 170 3160"
logo: images/BuWiFi-logo-black.svg
logowhite: images/BuWiFi-logo-white.svg
favicon: images/BuWiFi.ico
blogimage: images/company/busy-hands-typing.jpg
twitter: "https://www.twitter.com/buwifi/"
twitter_username: buwifi
linkedin: "https://www.linkedin.com/company/buwifi/"
instagram: "https://www.instagram.com/buwifi/"
telephone: "+905321703160"
jdlocation: "https://maps.google.com/maps?q=Fenerbah%C3%A7e,%20Yo%C4%9Furt%C3%A7uba%C5%9F%C4%B1%20Sokak%2018-1,%20Kad%C4%B1k%C3%B6y/%C4%B0stanbul&t=&z=13&ie=UTF8&iwloc=&output=embed"
og_image: images/company/wifi-shopping-mall.jpg

google_analytics: G-CQBBWRN64F

debug: false

# ----------------------------
# URL & BASEURL
# ----------------------------
# Uncomment production/development
# PRODUCTION
# url: "https://BuWiFi.com"
# baseurl: ""
# recaptcha2_sitekey: 6Leo-3IiAAAAANO2sQOcwv1-3LrK49YCMr3lYlH3

# DEVELOPMENT
url: "http://localhost:4000"
baseurl: ""
# recaptcha2_sitekey: 6LcldnIiAAAAAK1Nl81Hj0cTqpgBlX4YCYp6yfUn

# ----------------------------
# SASS/SCSS
# ----------------------------
sass:
  style_dir: _scss
  sass_dir: _scss
  style: :expanded

# ----------------------------
# MARKDOWN
# ----------------------------
markdown: kramdown
# ----------------------------
# PLUGINS
# ----------------------------
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-sass-converter
  - jekyll-paginate-v2
  - jekyll-archives

# ----------------------------
# Main blog pagination
# ----------------------------
paginate_path: "/blog/page:num/"
pagination:
  enabled: true
  per_page: 4
  sort_field: 'date'
  sort_reverse: true

# ----------------------------
# Jekyll Archives for categories & tags
# ----------------------------

# ----------------------------
# COLLECTIONS
# ----------------------------
collections:
  services:
    output: true
    order: 
      - guestwifi.md
      - analytics.md
      - communication.md
      - cdp.md
      - dataintegration.md
      - networkmanagement.md
      - speedtest.md
  industry:
    output: true
    order: 
      - shoppingmall.md
      - retailchain.md
      - restaurant.md
      - hospitality.md
      - venues.md
      - transportation.md
  jobs:
    output: true
    order: 
      - pythondeveloper.md
      - radiusengineer.md
      - frontend.md
  customers:
    output: true
    order: 
      - teknosa.md
      - emaar.md
